In [44]:
from pickle import load, dump

with open('../Data/data.pkl','rb') as file:
    X_train, y_train = load( file )
    X_test, y_test = load( file )

In [45]:
from pandas import concat

X_test_normal = X_test[['loan_amount', 'income']]
X_test_to_map = X_test[['ffiec_msa_md_median_family_income', 'aus_GUS', 'lien_status_Subordinate Lien', 'total_units_100-149', 'total_units_2',
       'total_units_25-49', 'total_units_3', 'total_units_4',
       'total_units_5-24', 'total_units_50-99', 'total_units_>149',
       'conforming_loan_limit_NC', 'preapproval_Preapproval Requested']]

test = concat( [ y_test, X_test_normal ], axis=1 )

test['aus_GUS'] = X_test_to_map['aus_GUS'].map( { 0:'No', 1: 'Si' } )
test['lien_status'] = X_test_to_map['lien_status_Subordinate Lien'].map( { 0:'First Lien', 1: 'Subordinate Lien' } )
test['conforming_limit'] = X_test_to_map['conforming_loan_limit_NC'].map( { 0:'C', 1: 'NC' } )
test['preapproval'] = X_test_to_map['preapproval_Preapproval Requested'].map( { 0:'Preapproval Not Requested', 1: 'Preapproval Requested' } )
test['action_taken'] = test['action_taken'].map( { 0:'Negado', 1: 'Aceptado' } )
test['med_fam_income'] = X_test['ffiec_msa_md_median_family_income']

def create_single_column(row):
    if row.sum() == 0: return 1
    else: return row.idxmax().replace('total_units_', '')

total_units = X_test_to_map[['total_units_100-149', 'total_units_2',
       'total_units_25-49', 'total_units_3', 'total_units_4',
       'total_units_5-24', 'total_units_50-99', 'total_units_>149']]

test['total_units'] = total_units.apply(create_single_column, axis=1).astype(str)

test

,action_taken,loan_amount,income,aus_GUS,lien_status,conforming_limit,preapproval,med_fam_income,total_units
190735,Aceptado,355000.0,174.0,No,First Lien,C,Preapproval Not Requested,105600,1
296603,Aceptado,385000.0,135.0,No,First Lien,C,Preapproval Not Requested,105600,1
216194,Aceptado,265000.0,100.0,No,First Lien,C,Preapproval Not Requested,89100,1
288437,Negado,255000.0,120.0,No,First Lien,C,Preapproval Not Requested,89100,1
321963,Aceptado,315000.0,86.0,No,First Lien,C,Preapproval Not Requested,71000,1
...,...,...,...,...,...,...,...,...,...
353057,Aceptado,625000.0,190.0,No,First Lien,C,Preapproval Not Requested,122300,1
64122,Negado,475000.0,120.0,No,First Lien,C,Preapproval Not Requested,97600,1
398797,Aceptado,415000.0,281.0,No,First Lien,C,Preapproval Not Requested,105600,1
183124,Negado,275000.0,63.0,No,First Lien,C,Preapproval Not Requested,105600,1
229687,Aceptado,325000.0,115.0,No,First Lien,C,Preapproval Requested,77400,1

In [46]:
X_train_normal = X_train[['loan_amount', 'income']]
X_train_to_map = X_train[['ffiec_msa_md_median_family_income', 'aus_GUS', 'lien_status_Subordinate Lien', 'total_units_100-149', 'total_units_2',
       'total_units_25-49', 'total_units_3', 'total_units_4',
       'total_units_5-24', 'total_units_50-99', 'total_units_>149',
       'conforming_loan_limit_NC', 'preapproval_Preapproval Requested']]

train = concat( [ y_train, X_train_normal ], axis=1 )

train['aus_GUS'] = X_train_to_map['aus_GUS'].map( { 0:'No', 1: 'Si' } )
train['lien_status'] = X_train_to_map['lien_status_Subordinate Lien'].map( { 0:'First Lien', 1: 'Subordinate Lien' } )
train['conforming_loan_limit'] = X_train_to_map['conforming_loan_limit_NC'].map( { 0:'C', 1: 'NC' } )
train['preapproval'] = X_train_to_map['preapproval_Preapproval Requested'].map( { 0:'Preapproval Not Requested', 1: 'Preapproval Requested' } )
train['action_taken'] = train['action_taken'].map( { 0:'Negado', 1: 'Aceptado' } )
train['med_fam_income'] = X_train['ffiec_msa_md_median_family_income']

def create_single_column(row):
    if row.sum() == 0: return 1
    else: return row.idxmax().replace('total_units_', '')

total_units = X_train_to_map[['total_units_100-149', 'total_units_2',
       'total_units_25-49', 'total_units_3', 'total_units_4',
       'total_units_5-24', 'total_units_50-99', 'total_units_>149']]

train['total_units'] = total_units.apply(create_single_column, axis=1).astype(str)

train

,action_taken,loan_amount,income,aus_GUS,lien_status,conforming_loan_limit,preapproval,med_fam_income,total_units
283565,Aceptado,255000.0,139.0,No,First Lien,C,Preapproval Not Requested,89100,1
304094,Negado,425000.0,110.0,No,First Lien,C,Preapproval Not Requested,97600,1
102544,Aceptado,95000.0,39.0,No,First Lien,C,Preapproval Not Requested,94100,1
9727,Aceptado,475000.0,107.0,No,First Lien,C,Preapproval Not Requested,89100,1
302086,Aceptado,345000.0,89.0,No,First Lien,C,Preapproval Requested,105600,2
...,...,...,...,...,...,...,...,...,...
218868,Aceptado,5000.0,55.0,No,Subordinate Lien,C,Preapproval Not Requested,105600,1
164706,Aceptado,195000.0,107.0,No,First Lien,C,Preapproval Not Requested,84300,1
256742,Aceptado,185000.0,224.0,No,First Lien,C,Preapproval Not Requested,122300,1
253456,Aceptado,155000.0,144.0,No,First Lien,C,Preapproval Not Requested,89100,1
178352,Aceptado,145000.0,253.0,No,First Lien,C,Preapproval Not Requested,94100,1

In [47]:
with open('../Data/data_eda.pkl','wb') as file:
    dump( train, file )
    dump( test, file )

In [1]:
from pickle import load
with open( '../Data/data_eda.pkl', 'rb' ) as file:
    train = load( file )
    test = load( file )